### ISSUE TITLE
使用时必须using否则就会内存保护

### ISSUE THREAD

**Issue by dongzhaosheng73** [ArcticLampyrid/MMKV.NET#5]
必须按照样例代码 外层使用using包裹 执行后释放否则就会内存保护

**Comment by ArcticLampyrid** [comment]
details?

**Comment by dongzhaosheng73** [comment]
I initialized Mmkv.Default several times within the thread, and I should either make it a static variable or put it in a container.
android does not encounter this problem when using multithreading

**Comment by ArcticLampyrid** [comment]
请问可否提供一下具体的代码、日志和报错信息？堆栈跟踪记录？
I don't think the wrapper did any magic.
It just call `MMKV::defaultMMKV`

**Comment by dongzhaosheng73** [comment]
> I initialized Mmkv.Default several times within the thread, and I should either make it a static variable or put it in a container.
> android does not encounter this problem when using multithreading

应该是我使用的问题，我在多个线程下执行了MMKV::defaultMMKV 导致了这个错误，我现在只在应用初始化的时候执行一次后就一直使用同一个MMKV实例就可以了。
